id: D47B4AAE4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:00:36+00:00'
last_modified: '2022-05-30T06:21:13.430817+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    300b:
      image_group_id: I1PD95959
      title: ལུགས་ཀྱི་བསྟན་བཅོས་ཤེས་རབ་སྡོང་བུ།
      total_pages: 1872
      order: 114
      base_file: 300b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
