id: P674CFA81
initial_creation_type: ocr
source_metadata:
  volumes:
    8f0bf80645e04b96aa4eed9b05b30b8b:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ལུགས་ཀྱི་བསྟན་བཅོས་ཤེས་རབ་སྡོང་བུ།
      total_pages: 1872
      volume_number: 114
